// angular/src/app/load-image/load-image.component.ts
import {Component, Input, ViewEncapsulation} from '@angular/core';

@Component({
  selector: 'angular-load-image',
  template: `
    <img class="thumb" [ngClass]="{ready: ready}" [src]="srcThumb"/>
    <img [src]="src" (load)="ready = true"/>`,
  styleUrls: ['load-image.component.scss'],
  encapsulation: ViewEncapsulation.ShadowDom
})
export class LoadImageComponent {
  @Input() src: string;
  @Input() srcThumb: string;

  ready = false;
}

// vue/src/components/LoadImage.vue
<template>
  <img class="thumb" v-bind:class="{ready: ready}" src="{{srcThumb}}"/>
  <img [src]="{{src}}" @load="load"/>
</template>

<script>
import Vue from 'vue';
import Component from 'vue-class-component';

@Component({
  props: {
    src: String,
    srcThumb: String
  },
  template: ``
})
export default class LoadImageComponent extends Vue {
  ready = false;

  load(): void {
    this.ready = true;
  }
}
</script>
