// image-carousel/react/src/App.js
import './App.css';

import React from 'react';

class App extends React.Component {
  constructor() {
    super();
    this.state = {
      index: 0,
    };
  }

  prev() {
    let index = this.state.index;
    index += 1;
    index %= 4;
    this.setState({ index });
  }

  next() {
    let index = this.state.index;
    index -= 1;
    if (index < 0) {
      index = 3;
    }
    this.setState({ index });
  }

  srcLink(index) {
    return `http://localhost:3200/assets/${index % 4}.jpg`;
  }

  srcThumbLink(index) {
    return `http://localhost:3200/thumbs/${index % 4}.jpg`;
  }

  render() {
    return (
      <div>
        <div className="actions">
          <button onClick={() => this.prev()}>Prev</button>
          <button onClick={() => this.next()}>Next</button>
        </div>

        <div className="grid">
          <angular-load-image src={this.srcLink(this.state.index)} src-thumb={this.srcThumbLink(this.state.index)} alt="angular">Loading Angular..</angular-load-image>
          <vue-load-image src={this.srcLink(this.state.index + 1)} src-thumb={this.srcThumbLink(this.state.index + 1)} alt="vue">Loading Vue..</vue-load-image>
          <react-load-image src={this.srcLink(this.state.index + 2)} src-thumb={this.srcThumbLink(this.state.index + 2)} alt="react">Loading React..</react-load-image>
          <javascript-load-image src={this.srcLink(this.state.index + 3)} src-thumb={this.srcThumbLink(this.state.index + 3)} alt="javascript">Loading JavaScript..</javascript-load-image>
        </div>
      </div>
    );
  }
}

export default App;

// carousel/angular-carousel/src/app/app.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  index = 0;

  prev() {
    this.index += 1;
    this.index %= 4;
  }

  next() {
    this.index -= 1;
    if (this.index < 0) {
      this.index = 3;
    }
  }
}

<div class="actions">
  <button (click)="prev()">Prev</button>
  <button (click)="next()">Next</button>
</div>

<div class="grid">
  <angular-load-image [attr.src]="index | imageIndex: 'assets'" [attr.src-thumb]="index | imageIndex: 'thumbs'" alt="angular">Loading Angular..</angular-load-image>
  <vue-load-image [attr.src]="(index + 1) | imageIndex: 'assets'" [attr.src-thumb]="(index + 1) | imageIndex: 'thumbs'" alt="vue">Loading Vue..</vue-load-image>
  <react-load-image [attr.src]="(index + 2) | imageIndex: 'assets'" [attr.src-thumb]="(index + 2) | imageIndex: 'thumbs'" alt="react">Loading React..</react-load-image>
  <javascript-load-image [attr.src]="(index + 3) | imageIndex: 'assets'" [attr.src-thumb]="(index + 3) | imageIndex: 'thumbs'" alt="javascript">Loading JavaScript..</javascript-load-image>
</div>
