// angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'angular-root',
  template: `
    <angular-load-image
      src="http://localhost:3200/angular.jpg"
      thumb="http://localhost:3200/angular-thumb.jpg"
      alt="angular">
    </angular-load-image>`,
})
export class AppComponent {
}

// react/src/App.js
import React, { Component } from 'react';
import LoadImage from './LoadImage';

class App extends Component {
  render() {
    return (
      <LoadImage
        src="http://localhost:3200/react.jpg"
        srcThumb="http://localhost:3200/react-thumb.jpg"
        alt="react">
      </LoadImage>
    );
  }
}

export default App;
