// load-image/react-load-image/src/LoadImage.js
import React from 'react';
import styled from 'styled-components';

import styles from './LoadImage.css';


const Image = styled.img`
  width: 400px;
  height: 300px;
`

const Thumb = styled.img`
  position: absolute;
  width: 400px;
  height: 300px;
  opacity: ${props => props.ready ? 0 : 1};
  transition: opacity .5s;
`

class LoadImage extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      ready: false,
    };
  }

  componentDidUpdate(prevProps) {
    if (this.props.src !== prevProps.src) {
      this.setState({ ready: false });
    }
  }

  render() {
    return (
      <div class={styles['load-image']}>
        <Thumb src={this.props.srcThumb} alt={this.props.alt} className="thumb" ready={this.state.ready}></Thumb>
        <Image src={this.props.src} alt={this.props.alt} onLoad={() => this.setState({ ready: true })} loading="lazy"></Image>
      </div>
    );
  }
}

export default LoadImage;

// load-image/vue-load-image/src/components/LoadImage.vue
<template>
  <div class="root" :ready="ready">
    <img :src="srcThumb" :alt="alt" class="thumb" />
    <img :src="src" :alt="alt" @load="ready = true" loading="lazy" />
  </div>
</template>

<style lang="scss" scoped>
.root {
  display: block;
  width: 400px;
  height: 300px;
}

div[ready] img.thumb {
  opacity: 0;
}

img {
  width: 400px;
  height: 300px;

  &.thumb {
    position: absolute;
    opacity: 1;
    transition: opacity 0.5s;
  }
}
</style>

<script>
import Vue from "vue";
import Component from "vue-class-component";

Vue.config.productionTip = false;

export default
@Component({
  props: {
    src: String,
    srcThumb: String,
    alt: String
  },
  watch: {
    src: function() {
      this.ready = false;
    }
  }
})
class LoadImage extends Vue {
  ready = false;
}
</script>
